services:
  neko:
    build: .
    restart: unless-stopped
    shm_size: 2048mb
    cap_add:
      - SYS_ADMIN
    ports:
      - '8080:8080'
      - '9222:9222'                    # Direct CDP access for Docker containers
      - '52000-52100:52000-52100/udp'
    networks:
      - browser-network
    # volumes:
      # Persistent browser profile storage (custom location)
      # - "chromium-profile:/tmp/chromium-profile"
    tmpfs:
      # Optimized tmpfs for fastest I/O
      - /tmp:exec,noatime,size=1g
      - /var/tmp:exec,noatime,size=256m
      - /home/neko/.cache:exec,noatime,size=256m
      - /tmp/chromium-profile:exec,noatime,size=512m
    mem_limit: 4g
    memswap_limit: 4g
    cpus: 2.0
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    # Startup optimization
    init: true
    # Security optimizations that can speed up startup
    security_opt:
      - seccomp:unconfined
    environment:
      # Screen dimensions (used by Xvfb, Neko, and video pipelines)
      SCREEN_WIDTH: 1024
      SCREEN_HEIGHT: 768
      # Neko-specific screen configuration
      NEKO_DESKTOP_SCREEN: "1024x768@15"
      NEKO_SCREEN_WIDTH: 1024
      NEKO_SCREEN_HEIGHT: 768
      # Optimized for fastest startup
      MALLOC_ARENA_MAX: 2
      MALLOC_MMAP_THRESHOLD_: 131072
      MALLOC_TRIM_THRESHOLD_: 262144
      # Disable unnecessary background services
      NEKO_HEALTH_CHECK: "false"
      # Use config file instead of individual environment variables
      NEKO_CONFIG: "/etc/neko/neko.yaml"
      # Force anonymous login and autoplay via environment variables
      NEKO_PASSWORD: ""
      NEKO_PASSWORD_ADMIN: ""
      NEKO_MEMBER_PROVIDER: "anonymous"

volumes:
  # Persistent storage for recordings
  - "./recordings:/storage"
networks:
  browser-network:
    driver: bridge

# volumes:
#   chromium-profile: