services:
  neko:
    build: .
    restart: unless-stopped
    shm_size: 1024mb
    cap_add:
      - SYS_ADMIN
    ports:
      - '8080:8080'
      - '9223:9223'                    # Socat proxy for external DevTools access
      - '52000-52100:52000-52100/udp'
    volumes:
      # Persistent browser profile storage (custom location)
      - "chromium-profile:/home/neko/chromium-profile"
    tmpfs:
      # Use smaller tmpfs for cache and temporary files to conserve RAM
      - /tmp:exec,size=256m
      - /var/tmp:exec,size=128m
      - /home/neko/.cache:exec,size=128m
    mem_limit: 2g
    memswap_limit: 2g
    cpus: 1.0
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    environment:
      # Low-resource optimizations
      MALLOC_ARENA_MAX: 1
      MALLOC_MMAP_THRESHOLD_: 65536
      MALLOC_TRIM_THRESHOLD_: 131072
      # Use config file instead of individual environment variables
      NEKO_CONFIG: "/etc/neko/neko.yaml"

volumes:
  chromium-profile: