services:
  neko:
    build: .
    restart: unless-stopped
    shm_size: 2048mb
    cap_add:
      - SYS_ADMIN
    ports:
      - '8080:8080'
      - '9223:9223'                    # Socat proxy for external DevTools access
      - '52000-52100:52000-52100/udp'
    # volumes:
      # Persistent browser profile storage (custom location)
      # - "chromium-profile:/tmp/chromium-profile"
    tmpfs:
      # Use smaller tmpfs for cache and temporary files to conserve RAM
      - /tmp:exec,size=512m
      - /var/tmp:exec,size=256m
      - /home/neko/.cache:exec,size=256m
    mem_limit: 4g
    memswap_limit: 4g
    cpus: 2.0
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    environment:
      # Screen dimensions (used by Xvfb, Neko, and video pipelines)
      SCREEN_WIDTH: 1024
      SCREEN_HEIGHT: 768
      # Optimized for 2 CPUs
      MALLOC_ARENA_MAX: 2
      MALLOC_MMAP_THRESHOLD_: 131072
      MALLOC_TRIM_THRESHOLD_: 262144
      # Use config file instead of individual environment variables
      NEKO_CONFIG: "/etc/neko/neko.yaml"
      # Force anonymous login and autoplay via environment variables
      NEKO_PASSWORD: ""
      NEKO_PASSWORD_ADMIN: ""
      NEKO_MEMBER_PROVIDER: "anonymous"

# volumes:
#   chromium-profile: